version: "3"

services:
  web:
    image: nginx
    container_name: ${PROJECT_NAME}-web
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./src/public:/src/public
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./php
    volumes:
      - ./src:/src

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    restart: always
    env_file: .env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/authentication.cnf:/etc/mysql/conf.d/authentication.cnf
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  redis:
      image: redis:latest
      container_name: ${PROJECT_NAME}-kvs
      restart: always
      volumes:
          - ./redis:/data
      ports:
          - "6379:6379"
      command: redis-server --appendonly yes